name: Sync Upstream

on:
  schedule:
    # 每天執行一次 (可根據需求調整 UTC 時間)
    - cron: "0 23 * * *"
  workflow_dispatch:
    # 允許手動觸發此 workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }} # 確保此 workflow 只在 fork 的專案上執行

    steps:
      # 步驟 1: Checkout 您的專案
      - name: Checkout target repo
        uses: actions/checkout@v4

      # 步驟 2: 使用社群開發的 Action 來同步上游變更
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          # 上游專案的 repository，格式為 owner/repo
          upstream_sync_repo: openbmc/openbmc
          # 上游專案要同步的 branch
          upstream_sync_branch: master
          # 您自己 fork 專案要接收更新的 branch
          target_sync_branch: master
          # 使用 GitHub 自動產生的權杖進行驗證
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 設定為 false 代表正式同步，非測試模式
          test_mode: false
